sky:
  wechat:
    appid: 'wxfa73124890036bfb'
    secret: 'd7a46e45242bb679ddb38eb66b044487'
    # 微信支付相关
    mchid: 1561414331 # 商户号
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606 # 商户证书序列号
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://1626ff09.r15.vip.cpolar.cn/notify/paySuccess # 回调地址, 支付成功后
    refundNotifyUrl: https://1626ff09.r15.vip.cpolar.cn/notify/refundSuccess
  redis:
    host: localhost
    port: 6379
#    password: '123456'
    auth: 123456
    database: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123456"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLxstLrpN2HLC9Tz7nq
    access-key-secret: rYBcqhI6Q8s3wdTu8RB5ydha1wDmLq
    bucket-name: skytakeoutxsa

